compile:
	npx hardhat compile
	npx hardhat run ignition/modules/Check.ts --network sepolia
	
deploy:
	npx hardhat run ignition/modules/Check.ts --network pharos-devnet

verify:
	npx hardhat verify --network sepolia 0x4Bf3f61e96E252b659e92511492490385308F723