compile:
	npx hardhat compile
	npx hardhat run ignition/modules/Check.ts --network sepolia
	
deploy:
	npx hardhat run ignition/modules/Check.ts --network pharos-devnet

verify:
	npx hardhat verify --network sepolia 0x819253a2ae3Fa6A1AF71021514994F2b95A83A88