compile:
	npx hardhat compile

deploy:
	npx hardhat run ignition/modules/Check.ts --network pharos-devnet

verify:
	npx hardhat verify --network pharos-devnet 0xfd4F95F894a856588074B96dde84484c307B2929